# Generated by Django 4.2.23 on 2025-07-24 07:43

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoundDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_document', models.CharField(max_length=100)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to=apps.core.models.upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LostDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('found_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.founddocument')),
                ('lost_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lostdocument')),
            ],
        ),
        migrations.AddField(
            model_name='lostdocument',
            name='contact_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_documents', to='core.usercontactinfo'),
        ),
        migrations.AddField(
            model_name='lostdocument',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.documenttype'),
        ),
        migrations.AddField(
            model_name='founddocument',
            name='contact_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_documents', to='core.usercontactinfo'),
        ),
        migrations.AddField(
            model_name='founddocument',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.documenttype'),
        ),
    ]
