# Generated by Django 4.2.23 on 2025-07-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founddocument',
            name='found_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
