# Generated by Django 5.2.7 on 2025-10-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founddocument',
            name='image',
        ),
        migrations.AddField(
            model_name='founddocument',
            name='image_blurred',
            field=models.ImageField(blank=True, null=True, upload_to='found_docs/blurred/'),
        ),
        migrations.AddField(
            model_name='founddocument',
            name='image_original',
            field=models.ImageField(default=1, upload_to='found_docs/originals/'),
            preserve_default=False,
        ),
    ]
