# Generated by Django 5.2.7 on 2025-10-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_founddocument_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founddocument',
            name='image_original',
            field=models.ImageField(upload_to='found_docs/'),
        ),
    ]
