# Generated by Django 5.2.7 on 2025-10-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_founddocument_image_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='founddocument',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founddocument',
            name='when_found',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founddocument',
            name='where_found',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lostdocument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_docs/'),
        ),
        migrations.AddField(
            model_name='lostdocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostdocument',
            name='when_lost',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostdocument',
            name='where_lost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
