# Generated by Django 5.2.7 on 2025-10-24 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_payment_contactaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostdocument',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lostdocument',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostdocument',
            name='premium_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_lost_documents', to='reports.payment'),
        ),
    ]
